# Generated by Django 5.2 on 2025-11-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carteira',
            old_name='saldo_inicial',
            new_name='saldo',
        ),
    ]
